### ISSUE TITLE
Input element value change not firing

### ISSUE THREAD

**Issue by lizylgit** [stephen31/virtual-keyboard-plugin#5]
Thanks for the virtual keyboard plugin.  I am testing this solution to be used with one of our touch screen devices.
I cannot get the onchange or oninput events to fire on the input box when the value changes. Want to enable  autocomplete when the user starts typing with the virtual keyboard. 
Are you able to help!
<div class="virtual-keyboard-hook" data-target-id="monId" data-keyboard-mapping="azerty">
<input id="monId"
         (oninput)="searching($event)"
         (onchange)="searching($event)"
         type="text" virtual-keyboard>
</div>

**Comment by stephen31** [comment]
Hi , thank for the feedback and sorry for the late response I was very very busy , yes since the library modify the attribute "value" of textara/input , a event is not triggered , i will add some hooks on the next version of the library ,so users will be able to register callbacks on value changes , for now i think you can use MutationObserver [](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver ) to trigger callback

**Comment by stephen31** [comment]
you can now listen to custom events send by the virtual keyboard since the v1.2.0 of the library , refer to readme for more infos
